# Generated by Django 5.0.3 on 2024-03-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0002_alter_pdffile_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfFileText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_text', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdf.pdffile')),
            ],
        ),
    ]
